openapi: 3.1.0
info:
  title: ECHOHUB API
  description: >-
    API Endpoints for the ECHOHUB Project. Team


    # Authentication

    Authentication is a process by which a system verifies the identity of a
    user accessing this API.       


    <!-- ReDoc-Inject: <security-definitions> -->
  version: v1
  termsOfService: https://example.com
  contact:
    name: ECHO Health Inc.
    url: https://echohealthinc.com
    email: Echo_Hub@echohealthinc.com
externalDocs:
  description: |
    description external docs text
  url: 'https://example.server.io'
servers:
  - url: /v1
  
paths:
  #Authorization
  /api/Authentication/v1/Authentication:
    $ref: paths/Authentication/api@RequestAuthentication@V1.yaml
  #eCheckPDF 
  /api/PDFDocs/v1/PDFDownload [For SelectPay]:
    $ref: paths/PDFDocs/api@v1@PDFDownloadSelectPay.yaml
  /api/PDFDocs/v1/PDFDownload [For Deluxe]:
    $ref: paths/PDFDocs/api@v1@PDFDownloadDeluxe.yaml
  /api/PDFDocs/v1/PDFDownload [For B2B]:
    $ref: paths/PDFDocs/api@v1@PDFDownloadB2B.yaml
components:
  securitySchemes:
    x-ApiKey:
      type: apiKey
      name: x-ApiKey
      description: The API key.
      in: header
    x-ClientKey:
      type: apiKey
      description: The client key.
      name: x-ClientKey
      in: header
    ApiKeyAuth:
      type: apiKey
      name: x-Authorization
      in: header
      description: Requests should pass an api_key header.  
    
tags: 
  #Authorization
  - name: Authorization 
    description: |
      This endpoint helps to generate the Authorization Token for accessing the endpoints. 
  #eCheckPDF
  - name:  eCheck PDF
    description: | 
       This endpoint allows the consumer Payee to get a PDF file of a Deluxe eCheck from the payment systems in ECHO Hub. The Payee can download the PDF file, print the eCheck and cash or deposit it just like a paper check. When the Payee logs into a payment system and makes the payment selection as eCheck, an eCheck is created and this API retrieves the PDF file. First, the data is validated in the ECHO Hub system and is then redirected to the Deluxe library in ECHO Hub. The Deluxe library will receive requests to get an eCheck PDF file from Deluxe. The PDF is retrieved, and ECHO Hub will send a success message along with the eCheck PDF file stream to the requested payment system and then the PDF file to the consumer Payee.       
